name: Build and Push to Amazon ECR

on:
  push:
    branches: [ "main" ] # Déclenche le build lors d'un push sur main
  pull_request:
    branches: [ "main" ] # Déclenche le build lors d'une merge sur main

env:
  IMAGE_TAG: ${{ github.sha }} 
  AWS_REGION: eu-north-1
  # Utilise le SHA du commit comme tag d'image

jobs:
  deploy:
    name: Build and Push
    runs-on: ubuntu-latest
    environment: aws_ecr_secret

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Debug secrets
      run: |
        echo "ECR_REPO is set: ${{ secrets.ECR_REPOSITORY_NAME != '' }}"
        echo "KEY_ID is set: ${{ secrets.AWS_ACCESS_KEY_ID != '' }}"
        echo "SECRET is set: ${{ secrets.AWS_SECRET_ACCESS_KEY != '' }}"
    # 1. Configuration des identifiants AWS
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}
        

    # 2. Connexion à Amazon ECR
    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v2

    # 3. Build, Tag et Push de l'image
    - name: Build, tag, and push image to Amazon ECR
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        ECR_REPOSITORY: ${{ secrets.ECR_REPOSITORY_NAME }}
      run: |
        docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
        docker tag $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG $ECR_REGISTRY/$ECR_REPOSITORY:latest
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:latest

    - name: Setup SSH key
      run: |
        echo "${{ secrets.EC2_SSH_PRIVATE_KEY }}" | base64 -d > /tmp/ssh_key
        cat /tmp/ssh_key
        chmod 600 /tmp/ssh_key

        
     # Copie uniquement le docker-compose.yml sur l'instance
    - name: Copy docker-compose to EC2
      uses: appleboy/scp-action@v0.1.7
      with:
        host: ${{ secrets.EC2_HOST }}
        username: root
        key_path: /tmp/ssh_key
        source: "docker-compose.yml"
        target: "/home/root/"

    
    - name: Deploy on EC2
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.EC2_HOST }}
        username: root
        key_path: /tmp/ssh_key
        command_timeout: 5m
        envs: ECR_REGISTRY,ECR_REPOSITORY,AWS_REGION,IMAGE_TAG,MYSQL_DATABASE,MYSQL_USER,MYSQL_PASSWORD,MYSQL_ROOT_PASSWORD,GHOST_URL
        script: |
          # Recrée le .env
          cat > /home/root/.env << EOF
          MYSQL_DATABASE=$MYSQL_DATABASE
          MYSQL_USER=$MYSQL_USER
          MYSQL_PASSWORD=$MYSQL_PASSWORD
          MYSQL_ROOT_PASSWORD=$MYSQL_ROOT_PASSWORD
          GHOST_URL=$GHOST_URL
          EOF

          # Authentification ECR
          aws ecr get-login-password --region $AWS_REGION | \
            docker login --username AWS --password-stdin $ECR_REGISTRY

          # Pull et redémarrage
          docker pull $ECR_REGISTRY/$ECR_REPOSITORY:latest
          docker compose down
          docker compose up -d